// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoo9R7ey8jMQlufEjzy76tYbOgxJdW24k',
    appId: '1:1042097751372:web:0c0a3042826228d28bbbe9',
    messagingSenderId: '1042097751372',
    projectId: 'd-chat-84fd0',
    authDomain: 'd-chat-84fd0.firebaseapp.com',
    storageBucket: 'd-chat-84fd0.firebasestorage.app',
    measurementId: 'G-6G25CPSFF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapvsUK7a6EppOeTOpG9a7a2DvPZlWh0I',
    appId: '1:1042097751372:android:d6e0dbc18b1150a58bbbe9',
    messagingSenderId: '1042097751372',
    projectId: 'd-chat-84fd0',
    storageBucket: 'd-chat-84fd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCaigEUDsJ9dKgHsEe86MzyOUcYmmCz7s',
    appId: '1:1042097751372:ios:565b018a9543be378bbbe9',
    messagingSenderId: '1042097751372',
    projectId: 'd-chat-84fd0',
    storageBucket: 'd-chat-84fd0.firebasestorage.app',
    iosBundleId: 'com.example.dChat',
  );
}
